---

- hosts: localhost
  connection: local
  gather_facts: True
  become: True
  vars:
    key_name: eng89_salem_ans
    region: eu-west-1
    image: ami-0565862bb4b547478
    id: "eng89_salem_bastion"
    sec_group: "sg-09e4effda28899af3"
    subnet_id: "subnet-0fa9c375e27c398ce"
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: facts
      block:

      - name: get instance gather_facts
        ec2_instance_facts:
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"
          region: "{{region}}"
        register: result

    - name: provisioning ec2 instances
      block:

      - name: upload public key to aws_access_key
        ec2_key:
          name: "{{key_name}}"
          key_material: "{{ lookup('file', '~/.ssh/eng89/{{ key_name }}.pub') }}"
          region: "{{region}}"
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"

      - name: provision instance
        ec2:
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"
          assign_public_ip: True
          key_name: "{{key_name}}"
          id: "{{id}}"
          vpc_subnet_id: "{{subnet_id}}"
          group_id: "{{sec_group}}"
          image: "{{image}}"
          instance_type: t2.micro
          region: "{{region}}"
          wait: True
          count: 1
          instance_tags:
            Name: eng89_salem_playbook_bastion

      tags: ['never', 'create_ec2']
